// Message à traduire dans le front
export enum ApiCodeResponse {
  TEST = 'api.result.test',
  COMMON_SUCCESS = 'api.success',
  NO_TOKEN_FOUNDED = 'api.security.error.no_token_found',
  USER_NOT_FOUND = 'api.security.error.user_not_found',
  TOKEN_EXPIRED = 'api.security.error.token_expired',
  SIGNUP_ERROR = 'api.security.error.sign-up',
  CREDENTIAL_DELETE_ERROR = 'api.security.error.credential-delete',
  USER_ALREADY_EXIST = 'api.security.error.user-already-exist',
  TOKEN_GEN_ERROR = 'api.security.error.token-gen',
  PAYLOAD_IS_NOT_VALID = 'api.validation.error',
  PAYLOAD_PARAM_IS_MISSING = 'api.validation.param.missing',
  USERNAME_IS_NOT_EMPTY = 'api.error.username.is-not-empty',
  USERNAME_MIN_LENGTH = 'api.error.username.min-length',
  USERNAME_MAX_LENGTH = 'api.error.username.max-length',
  PASSWORD_MIN_LENGTH = 'api.error.password.min-length',
  PASSWORD_MAX_LENGTH = 'api.error.password.max-length',
  PASSWORD_IS_NOT_EMPTY = 'api.error.password.is-not-empty',
  ACCOUNT_SIGNIN_SUCCESS = 'api.account.success',
  ACCOUNT_SIGNUP_SUCCESS = 'api.signup.success',

  CONTRACT_PAYLOAD_HOURLYRATE_IS_MANDATORY = 'api.contract.payload.validation-hourlyrate-is-mandatory',
  CONTRACT_PAYLOAD_PERKS_IS_NOT_STRING = 'api.contract.payload.validation-perks-is-not-string',
  CONTRACT_PAYLOAD_PERKS_LENGTH_ERROR = 'api.contract.payload.validation-perks-length-error',
  CONTRACT_PAYLOAD_STARTDATE_IS_NOT_VALID = 'api.contract.payload.validation-startdate-is-not-date',
  CONTRACT_PAYLOAD_STARTDATE_IS_MANDATORY = 'api.contract.payload.validation-startdate-is-mandatory',
  CONTRACT_PAYLOAD_EMPLOYEE_IS_MANDATORY = 'api.contract.payload.validation-employee-is-mandatory',
  CONTRACT_PAYLOAD_ID_IS_MANDATORY = 'api.contract.payload.validation-contract-id-is-mandatory',

  EMPLOYEE_PAYLOAD_FIRSTNAME_IS_NOT_STRING = 'api.employee.payload.validation-firstname-is-not-string',
  EMPLOYEE_PAYLOAD_FIRSTNAME_LENGTH_ERROR = 'api.employee.payload.validation-firstname-length-error',
  EMPLOYEE_PAYLOAD_FIRSTNAME_IS_MANDATORY = 'api.employee.payload.validation-firstname-is-mandatory',
  EMPLOYEE_PAYLOAD_LASTNAME_IS_NOT_STRING = 'api.employee.payload.validation-lastname-is-not-string',
  EMPLOYEE_PAYLOAD_LASTNAME_LENGTH_ERROR = 'api.employee.payload.validation-lastname-length-error',
  EMPLOYEE_PAYLOAD_LASTNAME_IS_MANDATORY = 'api.employee.payload.validation-lastname-is-mandatory',
  EMPLOYEE_PAYLOAD_BIRTHDATE_IS_NOT_VALID = 'api.employee.payload.validation-birthdate-invalid',
  EMPLOYEE_PAYLOAD_MAIL_IS_NOT_VALID = 'api.employee.payload.validation-mail-is-invalid',
  EMPLOYEE_PAYLOAD_MAIL_LENGTH_ERROR = 'api.employee.payload.validation-mail-length-error',
  EMPLOYEE_PAYLOAD_PHONE_LENGTH_ERROR = 'api.employee.payload.validation-phone-length-error',
  EMPLOYEE_PAYLOAD_IBAN_LENGTH_ERROR = 'api.employee.payload.validation-iban-length-error',
  EMPLOYEE_PAYLOAD_IBAN_IS_NOT_VALID = 'api.employee.payload.validation-iban-is-invalid',
  EMPLOYEE_PAYLOAD_ID_IS_MANDATORY = 'api.employee.payload.validation-id-is-mandatory',
  EMPLOYEE_PAYLOAD_ID_LENGTH_ERROR = 'api.employee.payload.validation-id-length-error',
}